server:
  port: 8080

spring:
  application:
    name: dynamic-thread-pool-demo
  rabbitmq:
    host: 192.168.30.166
    port: 5672
    username: guest
    password: guest

# 动态
dynamic-thread-pool:
  application_name: dynamic-thread-pool-demo
  admin:
    base_url: http://192.168.30.12:7701


logging:
  level:
    root: info
    com.coderandyli: debug